CREATE TABLE [dbo].[AuthorizeNetSilentPost] (
    [PostID]                 INT            IDENTITY (1, 1) NOT NULL,
    [x_response_code]        INT            NULL,
    [x_response_subcode]     INT            NULL,
    [x_response_reason_code] INT            NULL,
    [x_response_reason_text] NVARCHAR (255) NULL,
    [x_auth_code]            NVARCHAR (6)   NULL,
    [x_avs_code]             NVARCHAR (10)  NULL,
    [x_trans_id]             INT            NULL,
    [x_invoice_num]          NVARCHAR (20)  NULL,
    [x_description]          NVARCHAR (255) NULL,
    [x_amount]               MONEY          NULL,
    [x_method]               NVARCHAR (25)  NULL,
    [x_type]                 NVARCHAR (25)  NULL,
    [x_cust_id]              NVARCHAR (20)  NULL,
    [x_first_name]           NVARCHAR (50)  NULL,
    [x_last_name]            NVARCHAR (50)  NULL,
    [x_company]              NVARCHAR (50)  NULL,
    [x_address]              NVARCHAR (60)  NULL,
    [x_city]                 NVARCHAR (40)  NULL,
    [x_state]                NVARCHAR (40)  NULL,
    [x_zip]                  NVARCHAR (20)  NULL,
    [x_country]              NVARCHAR (60)  NULL,
    [x_phone]                NVARCHAR (25)  NULL,
    [x_fax]                  NVARCHAR (25)  NULL,
    [x_email]                NVARCHAR (255) NULL,
    [x_ship_to_first_name]   NVARCHAR (50)  NULL,
    [x_ship_to_last_name]    NVARCHAR (50)  NULL,
    [x_ship_to_company]      NVARCHAR (50)  NULL,
    [x_ship_to_address]      NVARCHAR (60)  NULL,
    [x_ship_to_city]         NVARCHAR (40)  NULL,
    [x_ship_to_state]        NVARCHAR (40)  NULL,
    [x_ship_to_zip]          NVARCHAR (20)  NULL,
    [x_ship_to_country]      NVARCHAR (60)  NULL,
    [x_tax]                  MONEY          NULL,
    [x_duty]                 MONEY          NULL,
    [x_freight]              MONEY          NULL,
    [x_tax_exempt]           NVARCHAR (10)  NULL,
    [x_po_num]               NVARCHAR (25)  NULL,
    [x_MD5_Hash]             NVARCHAR (255) NULL,
    [x_cavv_response]        NVARCHAR (255) NULL,
    [x_test_request]         NVARCHAR (255) NULL,
    [x_subscription_id]      NVARCHAR (255) NULL,
    [x_subscription_paynum]  NVARCHAR (255) NULL,
    CONSTRAINT [PK_AuthorizeNetSilentPost] PRIMARY KEY CLUSTERED ([PostID] ASC)
);