CREATE TABLE [dbo].[AuthTransactionLog] (
    [TransactionID]       INT              IDENTITY (1, 1) NOT NULL,
    [Status]              INT              NOT NULL,
    [SubscriptionID]      INT              NOT NULL,
    [Amount]              MONEY            NOT NULL,
    [CCNumberDisplay]     NVARCHAR (4)     NOT NULL,
    [PaymentID]           NVARCHAR (50)    NOT NULL,
    [PaymentErrorMessage] NVARCHAR (255)   NULL,
    [TransactionDate]     DATETIME         NOT NULL,
    [ClientIP]            NVARCHAR (15)    NULL,
    [PrimarySport]        INT              NOT NULL,
    [FirstName]           NVARCHAR (50)    NULL,
    [LastName]            NVARCHAR (50)    NULL,
    [OrganizationName]    NVARCHAR (255)   NULL,
    [Address]             NVARCHAR (255)   NULL,
    [City]                NVARCHAR (50)    NULL,
    [State]               NVARCHAR (50)    NULL,
    [PostalCode]          NVARCHAR (50)    NULL,
    [Country]             NVARCHAR (50)    NULL,
    [TaxID]               NVARCHAR (50)    NULL,
    [UserID]              UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PrimaryKey_4f8acfba-f9f3-4e33-a00f-0fbcbe5acbba] PRIMARY KEY CLUSTERED ([TransactionID] ASC),
    CONSTRAINT [FK_AuthTransactionLog_Subscriptions] FOREIGN KEY ([SubscriptionID]) REFERENCES [dbo].[Subscriptions] ([SubscriptionID]) ON DELETE CASCADE ON UPDATE CASCADE
);