CREATE TABLE [dbo].[Organizations] (
    [ID]               UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    [OrganizationName] NVARCHAR (255)   NOT NULL,
    [OrgText]          NTEXT            NULL,
    [Color]            NVARCHAR (10)    NULL,
    [Logo]             NVARCHAR (255)   NULL,
    [ContactName]      NVARCHAR (255)   NULL,
    [ContactPhone]     NVARCHAR (255)   NULL,
    [PrimaryAdminID]   UNIQUEIDENTIFIER NULL,
    [OrgPhoto]         NVARCHAR (255)   NULL,
    [Active]           BIT              NOT NULL,
    [DateCreated]      DATETIME         NOT NULL,
    [SiteType]         INT              NOT NULL,
    [OverlayLogo]      BIT              NOT NULL,
    [PrimarySport]     INT              NULL,
    [StreetAddress1]   NVARCHAR (100)   NULL,
    [StreetAddress2]   NVARCHAR (100)   NULL,
    [City]             NVARCHAR (100)   NULL,
    [StateProvince]    NVARCHAR (100)   NULL,
    [PostalCode]       NVARCHAR (20)    NULL,
    [Country]          NVARCHAR (100)   NULL,
    [OrgQuote]         NVARCHAR (255)   NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);