CREATE TABLE [dbo].[SessionVideos] (
    [SessionVideoID]      INT              IDENTITY (1, 1) NOT NULL,
    [SessionVideoKey]     UNIQUEIDENTIFIER CONSTRAINT [DF_SessionVideo_SessionVideoKey] DEFAULT (newid()) NOT NULL,
    [TokenID]             INT              NULL,
    [Action]              NVARCHAR (255)   NULL,
    [RecordingKey]        NVARCHAR (255)   NULL,
    [RecoringStatus]      INT              CONSTRAINT [DF_SessionVideo_RecoringStatus] DEFAULT ((0)) NOT NULL,
    [Title]               NVARCHAR (250)   NULL,
    [Notes]               NTEXT            NULL,
    [TelestrationDate]    DATETIME         CONSTRAINT [DF_SessionVideo_TelestrationDate] DEFAULT (getdate()) NOT NULL,
    [ActivityDate]        DATE             NULL,
    [StorageLocation]     NVARCHAR (255)   NULL,
    [StorageContainer]    NVARCHAR (255)   NULL,
    [StorageKey]          NVARCHAR (255)   NULL,
    [EncodingStatus]      INT              CONSTRAINT [DF_SessionVideo_EncodingStatus] DEFAULT ((0)) NOT NULL,
    [FramesKey]           UNIQUEIDENTIFIER NULL,
    [Deleted]             BIT              CONSTRAINT [DF_SessionVideo_Deleted] DEFAULT ((0)) NOT NULL,
    [IsPublic]            BIT              CONSTRAINT [DF_SessionVideo_IsPublic] DEFAULT ((0)) NOT NULL,
    [ShareWithCoaches]    BIT              CONSTRAINT [ColumnDefault_93b76422-5bda-4b3e-b352-8743322bdd92] DEFAULT ((0)) NOT NULL,
    [AthleteNotification] BIT              CONSTRAINT [ColumnDefault_8927aefc-3d79-4e0f-93be-c7dabb843f75] DEFAULT ((0)) NULL,
    [IsPrivate]           BIT              CONSTRAINT [ColumnDefault_719b9b77-fa71-4f70-91fe-0bf8420956cc] DEFAULT ((0)) NULL,
    [Sport]               NVARCHAR (255)   NULL,
    [EncodingCommand]     NVARCHAR (255)   NULL,
    [EncodeSubmit]        DATETIME         NULL,
    [EncodeStart]         DATETIME         NULL,
    [EncodeComplete]      DATETIME         NULL,
    [SessionTypeID]       INT              CONSTRAINT [ColumnDefault_04b8e89c-0fd5-4fdc-900d-89c321c88fa4] DEFAULT ((1)) NOT NULL,
    [Latitude]            DECIMAL (11, 9)  NULL,
    [Longitude]           DECIMAL (12, 9)  NULL,
    [OwnerID]             UNIQUEIDENTIFIER NULL,
    [TelestratedByUserID] UNIQUEIDENTIFIER NULL,
    [OrganizationID]      UNIQUEIDENTIFIER NULL,
    [SourceAppID]         UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PK_SessionVideo] PRIMARY KEY CLUSTERED ([SessionVideoID] ASC),
    CONSTRAINT [FK_SessionVideos_VstratorApps] FOREIGN KEY ([SourceAppID]) REFERENCES [dbo].[VstratorApps] ([ID])
);