CREATE TABLE [dbo].[Subscriptions] (
    [SubscriptionID]           INT              IDENTITY (1, 1) NOT NULL,
    [SubscriptionType]         INT              CONSTRAINT [ColumnDefault_b99966e4-6328-494b-8a8d-710b871375a4] DEFAULT ((0)) NOT NULL,
    [Status]                   INT              NULL,
    [StartDate]                DATETIME         NULL,
    [EndDate]                  DATETIME         NULL,
    [CanRenew]                 BIT              CONSTRAINT [ColumnDefault_a3429b83-1efe-4925-aedd-43fa403788c6] DEFAULT ((1)) NOT NULL,
    [Price]                    MONEY            NULL,
    [Frequency]                INT              CONSTRAINT [ColumnDefault_48b8b0c4-09df-409b-a14a-7c2642e17c4c] DEFAULT ((1)) NOT NULL,
    [RoleID]                   INT              NULL,
    [InvitationID]             INT              NULL,
    [IsTrial]                  BIT              CONSTRAINT [ColumnDefault_d62ee6a9-03ea-40ff-a3e5-9764dc648a95] DEFAULT ((0)) NOT NULL,
    [PromoCode]                NVARCHAR (50)    NULL,
    [IsActive]                 BIT              CONSTRAINT [ColumnDefault_06620283-1832-4848-9797-62b378f10401] DEFAULT ((1)) NOT NULL,
    [FirstName]                NVARCHAR (50)    NULL,
    [LastName]                 NVARCHAR (50)    NULL,
    [Organization]             NVARCHAR (255)   NULL,
    [Address]                  NVARCHAR (255)   NULL,
    [City]                     NVARCHAR (50)    NULL,
    [State]                    NVARCHAR (50)    NULL,
    [Country]                  NVARCHAR (50)    NULL,
    [TaxId]                    NVARCHAR (50)    NULL,
    [AcceptedTerms]            BIT              NOT NULL,
    [Cancelled]                BIT              CONSTRAINT [ColumnDefault_47b2a9f7-f7a6-4d5e-a531-266809201405] DEFAULT ((0)) NOT NULL,
    [CancelledDate]            DATETIME         NULL,
    [CreatedDate]              DATETIME         NULL,
    [CreatedIP]                NVARCHAR (50)    NULL,
    [PostalCode]               NVARCHAR (50)    NULL,
    [PlanName]                 NVARCHAR (255)   NULL,
    [CCNumberDisplay]          NVARCHAR (4)     NULL,
    [PaymentID]                NVARCHAR (50)    NULL,
    [PaymentResultCode]        NVARCHAR (50)    NULL,
    [PaymentResultMessage]     NVARCHAR (255)   NULL,
    [PromoPrice]               MONEY            NULL,
    [IsByPassPromo]            BIT              CONSTRAINT [ColumnDefault_8807b0fb-dd2d-4ba9-aebf-d2cb894b8c91] DEFAULT ((0)) NULL,
    [UserID]                   UNIQUEIDENTIFIER NULL,
    [OrganizationID]           UNIQUEIDENTIFIER NULL,
    [CCExpDate]                DATETIME         NULL,
    [PaymentEmail]             NVARCHAR (255)   NULL,
    [PrimarySport]             INT              NULL,
    [PaymentProcessorPlanName] NVARCHAR (100)   NULL,
    CONSTRAINT [PrimaryKey_dd615b64-98db-49fc-87ff-fb5db99b0aeb] PRIMARY KEY CLUSTERED ([SubscriptionID] ASC),
    CONSTRAINT [FK_Subscriptions_UserProfiles] FOREIGN KEY ([UserID]) REFERENCES [dbo].[UserProfiles] ([ID])
);