CREATE TABLE [dbo].[UserProfiles] (
    [ID]                            UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    [EmailAddress]                  NVARCHAR (255)   NULL,
    [FirstName]                     NVARCHAR (255)   NULL,
    [LastName]                      NVARCHAR (255)   NULL,
    [ProfileText]                   NTEXT            NULL,
    [ProfileDescription]            NTEXT            NULL,
    [ProfileColor]                  NVARCHAR (10)    NULL,
    [ProfilePicture]                NVARCHAR (255)   NULL,
    [ProfileLogo]                   NVARCHAR (255)   NULL,
    [LastIPAddress]                 NVARCHAR (50)    NULL,
    [DateCreated]                   DATETIME         DEFAULT (getdate()) NOT NULL,
    [MembershipUserID]              NVARCHAR (128)   NULL,
    [RegistrationCode]              NVARCHAR (50)    NULL,
    [PrimarySport]                  INT              DEFAULT ((2)) NULL,
    [ReferralCode]                  NVARCHAR (50)    NULL,
    [DebugUser]                     BIT              DEFAULT ((0)) NOT NULL,
    [SocialMediaID]                 NVARCHAR (255)   NULL,
    [PlayingLevel]                  NVARCHAR (100)   NULL,
    [StreetAddress1]                NVARCHAR (100)   NULL,
    [StreetAddress2]                NVARCHAR (100)   NULL,
    [City]                          NVARCHAR (100)   NULL,
    [StateProvince]                 NVARCHAR (100)   NULL,
    [PostalCode]                    NVARCHAR (20)    NULL,
    [Country]                       NVARCHAR (100)   NULL,
    [StripeID]                      NVARCHAR (100)   NULL,
    [ProfileVisibility]             INT              DEFAULT 31 NOT NULL,
    [DefaultClipVisibility]         INT              DEFAULT 31 NOT NULL,
    [DefaultVstratedClipVisibility] INT              DEFAULT 31 NOT NULL,
    [ProfileQuote]                  NVARCHAR (255)   NULL,
    [UserName]                      NVARCHAR (128)   NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);