CREATE PROCEDURE [dbo].[Dashboard_GetUserSummary]
@UserProfileID UNIQUEIDENTIFIER
AS
DECLARE @IsCoach AS BIT;
SET @IsCoach = dbo.IsCoach(@UserProfileID);
SELECT   CASE WHEN VideoType = 0
                   AND UploadedById = @UserProfileID
                   AND AthleteID <> @UserProfileID THEN 'Uploaded By Me for ' + AthleteFirstName + ' ' + AthleteLastName WHEN VideoType = 0
                                                                                                                              AND UploadedById = @UserProfileID
                                                                                                                              AND CoachID <> @UserProfileID THEN 'Uploaded By Me for ' + CoachFirstName + ' ' + CoachLastName WHEN VideoType = 0
                                                                                                                                                                                                                                   AND UploadedById <> @UserProfileID
                                                                                                                                                                                                                                   AND CoachID <> @UserProfileID THEN 'Uploads from ' + CoachFirstName + ' ' + CoachLastName WHEN VideoType = 0
                                                                                                                                                                                                                                                                                                                                  AND UploadedById <> @UserProfileID THEN 'Uploaded by ' + AthleteFirstName + ' ' + AthleteLastName WHEN VideoType = 0
                                                                                                                                                                                                                                                                                                                                                                                                                                         AND UploadedById = @UserProfileID
                                                                                                                                                                                                                                                                                                                                                                                                                                         AND AthleteID = @UserProfileID THEN 'Uploaded by Me' WHEN VideoType = 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   AND VideoSubtype = 4
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   AND CoachId = @UserProfileID
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   AND AthleteID <> @UserProfileID THEN 'Lesson sent to ' + AthleteFirstName + ' ' + AthleteLastName WHEN VideoType = 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          AND VideoSubtype = 4
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          AND CoachId <> @UserProfileID THEN 'Lesson Completed By ' + CoachFirstName + ' ' + CoachLastName WHEN VideoType = 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                AND AthleteID = @UserProfileID
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                AND CoachID = @UserProfileID THEN 'Created Vstrator Lesson' END AS [SummaryTitle],
         CASE WHEN VideoType = 0
                   AND UploadedById = @UserProfileID
                   AND AthleteID <> @UserProfileID THEN 'Videos Uploaded' WHEN VideoType = 0
                                                                               AND UploadedById = @UserProfileID
                                                                               AND CoachID <> @UserProfileID THEN 'Videos Uploaded' WHEN VideoType = 0
                                                                                                                                         AND UploadedById <> @UserProfileID
                                                                                                                                         AND CoachID <> @UserProfileID THEN 'Videos Uploaded' WHEN VideoType = 0
                                                                                                                                                                                                   AND UploadedById <> @UserProfileID THEN 'Videos Uploaded' WHEN VideoType = 0
                                                                                                                                                                                                                                                                  AND UploadedById = @UserProfileID
                                                                                                                                                                                                                                                                  AND AthleteID = @UserProfileID THEN 'Videos Uploaded' WHEN VideoType = 1
                                                                                                                                                                                                                                                                                                                             AND VideoSubtype = 4
                                                                                                                                                                                                                                                                                                                             AND CoachId = @UserProfileID
                                                                                                                                                                                                                                                                                                                             AND AthleteID <> @UserProfileID THEN 'Vstrator Lessons' WHEN VideoType = 1
                                                                                                                                                                                                                                                                                                                                                                                          AND VideoSubtype = 4
                                                                                                                                                                                                                                                                                                                                                                                          AND CoachId <> @UserProfileID THEN 'Vstrator Lessons' WHEN VideoType = 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                     AND AthleteID = @UserProfileID
                                                                                                                                                                                                                                                                                                                                                                                                                                                     AND CoachID = @UserProfileID THEN 'Vstrator Lessons' END AS [SummaryGrouping1],
         d.*
FROM     DashboardSummaryView AS d
WHERE    SummaryType = 'Video'
         AND (AthleteID = @UserProfileID
              OR CoachID = @UserProfileID)
UNION ALL
SELECT   CASE WHEN CoachID = @UserProfileID
                   AND ConnectionAccepted = 1 THEN 'Now connected to ' + AthleteFirstName + ' ' + AthleteLastName WHEN CoachID = @UserProfileID
                                                                                                                       AND ConnectionAccepted = 0
                                                                                                                       AND ConnectionAcceptedDate IS NULL THEN 'Waiting for response from ' + AthleteFirstName + ' ' + AthleteLastName WHEN CoachID = @UserProfileID
                                                                                                                                                                                                                                            AND ConnectionAccepted = 0
                                                                                                                                                                                                                                            AND ConnectionAcceptedDate IS NOT NULL THEN AthleteFirstName + ' ' + AthleteLastName + ' declined your invitiation' WHEN AthleteID = @UserProfileID
                                                                                                                                                                                                                                                                                                                                                                     AND ConnectionAccepted = 1 THEN 'Now connected to ' + CoachFirstName + ' ' + CoachLastName WHEN AthleteID = @UserProfileID
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     AND ConnectionAccepted = 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     AND ConnectionAcceptedDate IS NULL THEN 'Invitation to work with ' + CoachFirstName + ' ' + CoachLastName END AS [SummaryTitle],
         'New Connections' AS [SummaryGrouping1],
         d.*
FROM     DashboardSummaryView AS d
WHERE    SummaryType = 'Connection'
         AND ((@IsCoach = 0
               AND AthleteID = @UserProfileID)
              OR (@IsCoach = 1
                  AND CoachID = @UserProfileID))
UNION ALL
SELECT   'New Request from ' + AthleteFirstName + ' ' + AthleteLastName AS [SummaryTitle],
         'Vstrator Lessons' AS [SummaryGrouping1],
         d.*
FROM     DashboardSummaryView AS d
WHERE    SummaryType = 'Lesson Request'
         AND CoachID = @UserProfileID
ORDER BY SummaryDate, SummaryType;
RETURN 0;